version: '3'
services:
  postgres:
    image: postgres:12.1-alpine
    ports:
     - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - network_stepsdatafeed
  datafeed_backend:
    image: angelalonso/cns_datafeed_backend:v0.12
    ports:
     - "8080:8080"
    environment:
      DB_NAME_FILE: "secrets/db_feed_name"
      DB_USER_FILE: "secrets/db_feed_user"
      DB_PASS_FILE: "secrets/db_feed_pass"
      DB_PSQL_HOST: "postgres"
      DB_PSQL_PORT: "5432"
    networks:
      - network_stepsdatafeed
networks:
  network_stepsdatafeed:
    external: false
