version: '3'
services:
  postgres:
    # https://github.com/code-and-share/datafeed-db/tree/master/postgresql
    image: angelalonso/cns_datafeed_postgres:v0.01
    ports:
     - "5432:5432"
    networks:
      - network_stepsdatafeed
  datafeed_frontend:
    image: angelalonso/cns_datafeed_frontend:v0.10
    ports:
     - "9000:9000"
    environment:
      DB_PSQL_NAME: "feed"
      DB_PSQL_USER: "feed"
      DB_PSQL_PASS: "feeduser123"
      DB_PSQL_HOST: "0.0.0.0"
      DB_PSQL_PORT: "5432"
      PORT: "9000"
      FILES_SOURCE: "http://0.0.0.0:8080/files/"
    networks:
      - network_stepsdatafeed
  datafeed_backend:
    image: angelalonso/cns_datafeed_backend:v0.10
    ports:
     - "8080:8080"
    environment:
      DB_PSQL_NAME: "feed"
      DB_PSQL_USER: "feed"
      DB_PSQL_PASS: "feeduser123"
      DB_PSQL_HOST: "0.0.0.0"
      DB_PSQL_PORT: "5432"
    networks:
      - network_stepsdatafeed
networks:
  network_stepsdatafeed:
    external: false
