version: '3'
services:
  mysql:
    # https://github.com/code-and-share/datafeed-db/tree/master/mysql
    image: angelalonso/cns_mysql:v0.01
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - mysql_stepsdatafeed
  steps_datafeed:
    image: angelalonso/cns_stepsdatafeed:v0.01
    ports:
     - "9000:9000"
    environment:
      PORT: 9000
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASS: "secret"
      DB_NAME: "Paths"
    networks:
      - mysql_stepsdatafeed
networks:
  mysql_stepsdatafeed:
    external: false
